#!/usr/bin/env python3
"""
Generate V2 Static Website
Reference: EWC V2
"""

import os
import json
import shutil
from pathlib import Path
from datetime import datetime

OUTPUT_DIR = Path(r"C:\Users\Brandon Adams\EWC_Database_v2")
WEBSITE_DIR = OUTPUT_DIR / "taxonomy_output_v2" / "website"
DATA_DIR = OUTPUT_DIR / "taxonomy_output_v2" / "data"

def slugify(text):
    import re
    text = text.lower()
    text = re.sub(r'[^\w\s-]', '', text)
    text = re.sub(r'[\s_]+', '-', text)
    return text[:50]

def load_data():
    print("Loading data...")
    with open(DATA_DIR / "metadata.json", "r") as f:
        metadata = json.load(f)
    
    with open(OUTPUT_DIR / "derived_taxonomy_v2.json", "r", encoding='utf-8') as f:
        taxonomy = json.load(f)
        
    with open(OUTPUT_DIR / "cluster_assignments_v2.json", "r", encoding='utf-8') as f:
        assignments = json.load(f)

    # Group assignments by subcluster
    # Subcluster V2 ID: f"T1-{c_id}_T2-{s_id}"
    grouped_articles = {}
    for a in assignments:
        c_id = a['cluster']
        s_id = a['subcluster']
        key = f"T1-{c_id}_T2-{s_id}"
        if key not in grouped_articles:
            grouped_articles[key] = []
        grouped_articles[key].append(a)
        
    return metadata, taxonomy, grouped_articles

def generate_css():
    return """
:root { --primary: #2c3e50; --secondary: #3498db; --bg: #f8f9fa; --text: #333; }
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: system-ui, sans-serif; line-height: 1.6; color: var(--text); background: var(--bg); }
.container { max-width: 1200px; margin: 0 auto; padding: 20px; }
header { background: var(--primary); color: white; padding: 20px 0; margin-bottom: 30px; }
header h1 { font-size: 1.8rem; }
.card { background: white; border-radius: 8px; padding: 25px; margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.05); }
.grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(300px, 1fr)); gap: 20px; }
a { color: var(--secondary); text-decoration: none; }
a:hover { text-decoration: underline; }
.badge { display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 0.8rem; background: #e9ecef; }
h2 { color: var(--primary); border-bottom: 2px solid var(--secondary); padding-bottom: 10px; margin-bottom: 20px; }
.article-list { list-style: none; }
.article-list li { padding: 10px 0; border-bottom: 1px solid #eee; }
.viz-container { width: 100%; height: 500px; background: #fff; position: relative; border-radius: 8px; overflow: hidden; }
nav ul { list-style: none; display: flex; gap: 20px; }
nav a { color: white; font-weight: 500; }
footer { text-align: center; color: #777; padding: 40px 0; font-size: 0.9rem; }
/* Map styles */
.map-point { position: absolute; width: 10px; height: 10px; border-radius: 50%; transform: translate(-50%, -50%); cursor: pointer; transition: transform 0.2s; }
.map-point:hover { transform: translate(-50%, -50%) scale(1.5); z-index: 10; border: 1px solid #fff; }
.tooltip { position: fixed; background: rgba(0,0,0,0.8); color: white; padding: 5px 10px; border-radius: 4px; pointer-events: none; font-size: 0.8rem; z-index: 100; display: none; }
.legend { display: flex; flex-wrap: wrap; gap: 10px; font-size: 0.8rem; margin-top: 10px; }
.legend-item { display: flex; align-items: center; gap: 5px; }
.color-dot { width: 10px; height: 10px; border-radius: 50%; }
"""

def generate_js():
    return """
const Viz = {
    showTooltip(e, text) {
        let el = document.getElementById('tooltip');
        if(!el) { el = document.createElement('div'); el.id='tooltip'; el.className='tooltip'; document.body.appendChild(el); }
        el.innerHTML = text; el.style.display='block';
        el.style.left = (e.pageX + 10) + 'px'; el.style.top = (e.pageY + 10) + 'px';
    },
    hideTooltip() { const el=document.getElementById('tooltip'); if(el) el.style.display='none'; },
    slugify(text) {
        return text.toLowerCase().replace(/[^\\w\\s-]/g, '').replace(/[\\s_]+/g, '-');
    }
};
"""

def render_html(title, content, nav_path="../"):
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} - EWC v2</title>
    <link rel="stylesheet" href="{nav_path}css/style.css">
    <script src="{nav_path}js/app.js"></script>
</head>
<body>
    <header>
        <div class="container">
            <h1>EWC Database v2</h1>
            <nav>
                <ul>
                    <li><a href="{nav_path}index.html">Dashboard</a></li>
                    <li><a href="{nav_path}clusters/index.html">Clusters</a></li>
                </ul>
            </nav>
        </div>
    </header>
    <div class="container">
        {content}
    </div>
    <footer>
        <div class="container">Generated by EWC v2 Engine</div>
    </footer>
</body>
</html>
"""

def generate_viz_html(coords_file, colors_file):
    return f"""
    <div class="card">
        <h2>Taxonomy Landscape</h2>
        <div id="embedding-map" class="viz-container"></div>
        <div id="legend" class="legend"></div>
        <script>
            Promise.all([
                fetch('{coords_file}').then(r=>r.json()),
                fetch('{colors_file}').then(r=>r.json())
            ]).then(([coords, colors]) => {{
                const map = document.getElementById('embedding-map');
                const legend = document.getElementById('legend');
                
                // Render points
                coords.forEach(p => {{
                    const el = document.createElement('div');
                    el.className = 'map-point';
                    el.style.left = p.x + '%';
                    el.style.top = p.y + '%';
                    el.style.backgroundColor = colors.by_name[p.primary_name] || '#ccc';
                    
                    const pSlug = Viz.slugify(p.primary_id + '-' + p.primary_name);
                    const sSlug = Viz.slugify(p.name);
                    
                    el.onclick = () => window.location.href = '{coords_file.replace("data/coords_2d.json", "clusters/")}' + 
                        pSlug + '/' + sSlug + '.html';
                        
                    el.onmouseover = (e) => Viz.showTooltip(e, `<b>${{p.name}}</b><br>${{p.primary_name}}<br>${{p.article_count}} articles`);
                    el.onmouseout = Viz.hideTooltip;
                    map.appendChild(el);
                }});
                
                // Render legend
                colors.primaries.forEach(c => {{
                    const item = document.createElement('div');
                    item.className = 'legend-item';
                    item.innerHTML = `<div class="color-dot" style="background:${{c.color}}"></div>${{c.name}}`;
                    legend.appendChild(item);
                }});
            }});
        </script>
    </div>
    """

def main():
    print("Generating website...")
    
    # Setup dirs
    # if WEBSITE_DIR.exists(): shutil.rmtree(WEBSITE_DIR)
    os.makedirs(WEBSITE_DIR / "css", exist_ok=True)
    os.makedirs(WEBSITE_DIR / "js", exist_ok=True)
    os.makedirs(WEBSITE_DIR / "clusters", exist_ok=True)
    
    # Write assets
    with open(WEBSITE_DIR / "css/style.css", "w") as f: f.write(generate_css())
    with open(WEBSITE_DIR / "js/app.js", "w") as f: f.write(generate_js())
    
    # Load data
    metadata, taxonomy, content_map = load_data()
    
    # 1. Dashboard (Index)
    viz_html = generate_viz_html("data/coords_2d.json", "data/colors.json")
    
    cluster_cards = ""
    for p in metadata['primaries']:
        # Ensure unique slug by prepending ID (e.g. p0-database)
        p_slug = slugify(f"{p['id'].lower()}-{p['name']}")
        cluster_cards += f"""
        <div class="card">
            <h3><a href="clusters/{p_slug}/index.html" style="color:var(--primary)">{p['name']}</a></h3>
            <p style="color:#777">{sum(s['article_count'] for s in p['subclusters'])} articles</p>
            <div style="margin-top:10px; display:flex; flex-wrap:wrap; gap:5px">
                {" ".join([f'<span class="badge" style="background:{p["color"]}20; color:{p["color"]}">{s["name"]}</span>' for s in p['subclusters'][:5]])}
            </div>
        </div>
        """
        
    index_html = render_html("Dashboard", f"""
        <div style="margin-bottom:30px">
            <h2>Welcome to EWC v2</h2>
            <p>1536-dimensional semantic analysis of {metadata['total_subclusters']} subclusters.</p>
        </div>
        {viz_html}
        <h2>Primary Clusters</h2>
        <div class="grid">{cluster_cards}</div>
    """, nav_path="")
    
    with open(WEBSITE_DIR / "index.html", "w", encoding='utf-8') as f: f.write(index_html)
    
    # 2. Clusters Index
    with open(WEBSITE_DIR / "clusters/index.html", "w", encoding='utf-8') as f:
        f.write(render_html("All Clusters", f'<div class="grid">{cluster_cards}</div>', nav_path="../"))

    # 3. Cluster Pages & Subcluster Pages
    for p in metadata['primaries']:
        p_slug = slugify(f"{p['id'].lower()}-{p['name']}")
        p_dir = WEBSITE_DIR / f"clusters/{p_slug}"
        os.makedirs(p_dir, exist_ok=True)
        
        # Primary Page
        sub_cards = ""
        for s in p['subclusters']:
            s_slug = slugify(s['name'])
            sub_cards += f"""
            <div class="card">
                <h3><a href="{s_slug}.html">{s['name']}</a></h3>
                <p>{s['article_count']} articles</p>
            </div>
            """
            
            # Subcluster Detail Page
            s_articles = content_map.get(s['id'], [])
            article_list = '<ul class="article-list">'
            for a in s_articles:
                article_list += f"""
                <li>
                    <div><strong>{a['title']}</strong></div>
                    <div style="font-size:0.85rem; color:#666">
                        Topic: {a.get('existing_primary_topic','N/A')}
                    </div>
                </li>
                """
            article_list += '</ul>'
            
            sub_html = render_html(s['name'], f"""
                <div style="margin-bottom:20px"><a href="index.html">← Back to {p['name']}</a></div>
                <div class="card">
                    <h2>{s['name']}</h2>
                    <p>{len(s_articles)} articles</p>
                </div>
                <div class="card">
                    <h3>Articles</h3>
                    {article_list}
                </div>
            """, nav_path="../../")
            
            with open(p_dir / f"{s_slug}.html", "w", encoding='utf-8') as f: f.write(sub_html)
            
        # Write Primary Index
        p_html = render_html(p['name'], f"""
            <div style="margin-bottom:20px"><a href="../index.html">← Back to Clusters</a></div>
            <h1>{p['name']}</h1>
            <div class="grid">{sub_cards}</div>
        """, nav_path="../../")
        with open(p_dir / "index.html", "w", encoding='utf-8') as f: f.write(p_html)
        
    print("Website generated!")

if __name__ == "__main__":
    main()
